# Image: everbot/archlinux
FROM scratch
MAINTAINER everbot

# this doesn't work anymore 2017-01-11
# ADD https://github.com/everbot/dockerfiles/releases/download/2017-01-11/archlinux-2017-01-11.tar.gz /

# so we have to build this base image locally and push it to docker hub
ADD archlinux-2017-01-11.tar.gz /

CMD ["/bin/bash"]

