# Image: everbot/archlinux
FROM scratch
MAINTAINER everbot
ADD https://github.com/everbot/dockerfiles/releases/download/2017-01-11/archlinux-2017-01-11.tar.gz /
# ADD archlinux-2017-01-11.tar.gz /

CMD ["/bin/bash"]

